In [6]:
# mass balance

import cobra
import pandas as pd

model = cobra.io.read_sbml_model("Helicobacter_pylori.xml")

from collections import defaultdict

imbalanced_reactions = []

for rxn in model.reactions:
    balance = defaultdict(float)
    
    for met, coeff in rxn.metabolites.items():

        if met.formula:
            try:
                elements = met.elements
                
                for element, count in elements.items():
                    balance[element] += coeff * count
            except Exception:
                pass

# remove very small numerical values
balance = {
    element: round(value, 6)
    for element, value in balance.items()
    if abs(value) > 1e-6
}

if balance:
    imbalanced_reactions.append({
        "Reaction" : rxn.id,
        "Name" : rxn.name,
        "Imbalance" : balance
    })

mass_balance_df = pd.DataFrame(imbalanced_reactions)

print("Total reactions : ", len(model.reactions))
print("Mass-imbalanced reactions : " , len(mass_balance_df))

'' is not a valid SBML 'SId'.

Total reactions :  1025
Mass-imbalanced reactions :  1

In [8]:
print("Mass-imbalanced reactions : " , mass_balance_df)

Mass-imbalanced reactions :       Reaction        Name                                          Imbalance
0  biomass525  biomass525  {'C': -41.423097, 'H': -63.273871, 'N': -10.95...

In [10]:
mass_balance_df.head(20)

     Reaction        Name                                          Imbalance
0  biomass525  biomass525  {'C': -41.423097, 'H': -63.273871, 'N': -10.95...

In [12]:
# biomass rxn is imbalance

In [18]:
# charge balance
charge_imbalanced = []

for rxn in model.reactions:

    total_charge = 0

    for met, coeff in rxn.metabolites.items():

        if met.charge is not None:
            total_charge += coeff * met.charge

    total_charge = round(total_charge, 6)

    if abs(total_charge) > 1e-6:

        charge_imbalanced.append({
            "Reaction": rxn.id,
            "Name": rxn.name,
            "Charge_imbalance": total_charge
        })

charge_imbalance_df = pd.DataFrame(charge_imbalanced)

print("Total reactions:", len(model.reactions))
print("Charge-imbalanced reactions:", charge_imbalance_df)
print(len(charge_imbalance_df))

Total reactions: 1025
Charge-imbalanced reactions:          Reaction                                            Name  \
0          DM_btn                               Demand for biotin
1     DM_thmpp(c)        demand reaction for Thiamine diphosphate
2      EX_acac(e)                           Acetoacetate exchange
3       EX_akg(e)                         2-Oxoglutarate exchange
4    EX_alaasp(e)                   L-alanyl-L-aspartate exchange
5    EX_alaglu(e)                   L-alanyl-L-glutamate exchange
6     EX_arg_L(e)                             L-Arginine exchange
7     EX_asp_L(e)                            L-Aspartate exchange
8       EX_btn(e)                                 Biotin exchange
9       EX_but(e)                      Butyrate (n-C4:0) exchange
10      EX_ca2(e)                                Calcium exchange
11      EX_cd2(e)                                Cadmium exchange
12       EX_cl(e)                  exchange reaction for Chloride
13  EX_cobalt2(e)                                   Co2+ exchange
14      EX_cu2(e)                                   Cu2+ exchange
15     EX_ddca(e)                                laurate exchange
16      EX_fe2(e)                                       EX_fe2(u)
17      EX_fe3(e)                                   Fe3+ exchange
18      EX_for(e)                                Formate exchange
19      EX_fum(e)                  exchange reaction for fumarate
20     EX_glcn(e)                            D-Gluconate exchange
21    EX_glu_L(e)                            L-Glutamate exchange
22   EX_glyasp(e)                     Glycyl-L-aspartate exchange
23   EX_glyglu(e)                     Glycyl-L-glutamate exchange
24        EX_h(e)                    exchange reaction for proton
25     EX_hdca(e)                Hexadecanoate (n-C16:0) exchange
26      EX_hg2(e)                                   Hg2+ exchange
27   EX_ind3ac(e)                       Indole-3-acetate exchange
28        EX_k(e)                                     K+ exchange
29    EX_lac_L(e)                              L-Lactate exchange
30    EX_lys_L(e)                               L-Lysine exchange
31    EX_mal_L(e)                            Exchange of L-malate
32      EX_mg2(e)                                     Mg exchange
33      EX_mn2(e)                                   Mn2+ exchange
34      EX_na1(e)                    exchange reaction for Sodium
35      EX_nac(e)                             Nicotinate exchange
36      EX_nh4(e)                                Ammonia exchange
37      EX_ni2(e)                                   Ni2+ exchange
38      EX_no2(e)                                Nitrite exchange
39    EX_ocdca(e)    echange reaction for octadecanoate (n-C18:0)
40      EX_orn(e)                              Ornithine exchange
41       EX_pb(e)                                   Lead exchange
42       EX_pi(e)                              Phosphate exchange
43     EX_pime(e)                               Pimelate exchange
44      EX_ppi(e)                       exchange reaction for ppi
45      EX_pyr(e)                               Pyruvate exchange
46      EX_so4(e)                                Sulfate exchange
47     EX_succ(e)                              Succinate exchange
48      EX_thm(e)                   exchange reaction for Thiamin
49    EX_ttdca(e)  exchange reaction for tetradecanoate (n-C14:0)
50      EX_zn2(e)                                   Zinc exchange
51     biomass525                                      biomass525

    Charge_imbalance
0           1.000000
1           2.000000
2           1.000000
3           2.000000
4           1.000000
5           1.000000
6          -1.000000
7           1.000000
8           1.000000
9           1.000000
10         -2.000000
11         -2.000000
12          1.000000
13         -2.000000
14         -2.000000
15          1.000000
16         -2.000000
17         -3.000000
18          1.000000
19          2.000000
20          1.000000
21          1.000000
22          1.000000
23          1.000000
24         -1.000000
25          1.000000
26         -2.000000
27          1.000000
28         -1.000000
29          1.000000
30         -1.000000
31          2.000000
32         -2.000000
33         -2.000000
34         -1.000000
35          1.000000
36         -1.000000
37         -2.000000
38          1.000000
39          1.000000
40         -1.000000
41         -2.000000
42          2.000000
43          2.000000
44          3.000000
45          1.000000
46          2.000000
47          2.000000
48         -1.000000
49          1.000000
50         -2.000000
51          1.116622
52

In [20]:
# internal rxns
internal_charge_imbalanced = charge_balance_df[
    ~charge_balance_df["Reaction"].str.startswith(("EX_", "DM_"))
]

print("Total charge-imbalanced:", len(charge_balance_df))
print("EX reactions:", charge_balance_df["Reaction"].str.startswith("EX_").sum())
print("DM reactions:", charge_balance_df["Reaction"].str.startswith("DM_").sum())
print("Other reactions:", len(internal_charge_imbalanced))

internal_charge_imbalanced

Total charge-imbalanced: 52
EX reactions: 49
DM reactions: 2
Other reactions: 1

      Reaction        Name  Charge_imbalance
51  biomass525  biomass525          1.116622